import { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { cleanSongTitle } from '@/utils/cleanSongTitle';
import { getAllRecords, getRecordById } from '@/lib/records';

interface PageProps {
  params: Promise<{ id: string }>;
}

// Pre-render a share page for every record in the archive.
export function generateStaticParams() {
  return getAllRecords().map((record) => ({ id: record.id }));
}

function getRecord(id: string) {
  return getRecordById(id);
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { id } = await params;
  const record = getRecord(id);

  if (!record) {
    return {
      title: 'Record Not Found - For the Record',
    };
  }

  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || process.env.NEXT_PUBLIC_BASE_URL || 'https://fortherecord.fm';
  const title = `${cleanSongTitle(record.song_title)} by ${record.artist} — For ${record.for_name}`;
  // Use reflection text as description for richer preview, fall back to lyrics
  const description = record.reflection_text?.substring(0, 200) || record.lyric_excerpt?.substring(0, 140) || `${cleanSongTitle(record.song_title)} by ${record.artist}`;
  // Use the dynamic OG image route (generated by opengraph-image.tsx)
  const ogImageUrl = `${siteUrl}/card/${id}/opengraph-image`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      images: [
        {
          url: ogImageUrl,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
      url: `${siteUrl}/card/${id}`,
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImageUrl],
    },
  };
}

export default async function CardPage({ params }: PageProps) {
  const { id } = await params;
  // Redirect to home page with card query param to maintain existing behavior
  redirect(`/?card=${id}`);
}

