/**
 * Script to recompute background colors for all seed records
 * Uses the new deterministic color extraction algorithm
 *
 * Usage: npx tsx scripts/recomputeSeedColors.ts
 */

import { seedRecords } from '../data/seedRecords';
import fs from 'fs/promises';
import path from 'path';

// Server URL (adjust if needed)
const API_URL = process.env.API_URL || 'http://localhost:3000';

async function recomputeSeedColors() {
  console.log(`\n🎨 Recomputing colors for ${seedRecords.length} seed records...\n`);

  const updatedRecords = [];
  let successCount = 0;
  let fallbackCount = 0;
  let errorCount = 0;

  for (let i = 0; i < seedRecords.length; i++) {
    const record = seedRecords[i];
    const progress = `[${i + 1}/${seedRecords.length}]`;

    // Skip non-lyric cards
    if (record.cardType !== 'lyric' && record.cardType !== undefined && record.cardType !== 'lyric') {
      console.log(`${progress} ⏭️  Skipping ${record.cardType} card: ${record.song_title || record.logoText || record.id}`);
      updatedRecords.push(record);
      continue;
    }

    console.log(`${progress} Processing: ${record.artist} - ${record.song_title}`);

    if (!record.album_art_url) {
      console.warn(`  ⚠️  No album art URL, keeping existing color: ${record.background_color}`);
      updatedRecords.push(record);
      errorCount++;
      continue;
    }

    try {
      // Call color extraction API
      const response = await fetch(`${API_URL}/api/colors/extract`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ imageUrl: record.album_art_url }),
      });

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }

      const colorData = await response.json();

      if (colorData.method === 'extraction') {
        console.log(
          `  ✓ ${colorData.paletteKey} (${colorData.family}) - ${colorData.bgColor} ${
            colorData.cached ? '[cached]' : ''
          }`
        );
        successCount++;
      } else {
        console.log(
          `  ⚡ ${colorData.paletteKey} (${colorData.family}) - ${colorData.bgColor} [fallback]`
        );
        fallbackCount++;
      }

      updatedRecords.push({
        ...record,
        background_color: colorData.bgColor,
      });

      // Rate limit (be gentle with the API and external CDNs)
      await new Promise((resolve) => setTimeout(resolve, 100));
    } catch (error: any) {
      console.error(`  ✗ Error: ${error.message}, keeping existing color`);
      updatedRecords.push(record);
      errorCount++;
    }
  }

  // Generate updated TypeScript file
  const outputPath = path.join(process.cwd(), 'data', 'seedRecords.ts');

  // Format the records array for better readability
  const recordsJson = JSON.stringify(updatedRecords, null, 2)
    // Fix Date objects
    .replace(/"created_at":\s*"([^"]+)"/g, (_, date) => `"created_at": new Date("${date}")`);

  const fileContent = `// Auto-generated by recomputeSeedColors.ts on ${new Date().toISOString()}
// ${successCount} extracted, ${fallbackCount} fallback, ${errorCount} errors
import { Record } from "@/types/record";

// Seed data inspired by screenshot layout
// Note: Lyric excerpts are placeholder text to demonstrate layout and avoid copyright issues
export const seedRecords: Record[] = ${recordsJson};
`;

  await fs.writeFile(outputPath, fileContent, 'utf-8');

  console.log(`\n✓ Updated ${outputPath}`);
  console.log(`\nResults:`);
  console.log(`  ✓ Successfully extracted: ${successCount}`);
  console.log(`  ⚡ Fallback used: ${fallbackCount}`);
  console.log(`  ✗ Errors: ${errorCount}`);
  console.log(`  📦 Total processed: ${updatedRecords.length}`);
}

// Run the script
recomputeSeedColors().catch((error) => {
  console.error('\n❌ Script failed:', error);
  process.exit(1);
});
